name: reed
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn=1.*
  - seaborn
  - statsmodels
  - scipy
  - pip

  - pip:
    - econml>=0.9
    - xbart
    - tqdm
    - interpret
    - scikit-optimize
    - pyreadstat
    - jupyter_contrib_nbextensions
    - jupyter-book
    - papermill
variables:
  JUPYTER_CONFIG_PATH: config

  