name: reed
channels:
  - defaults
dependencies:
  - python
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn=0.23.2 # needed for compatibility with scikit-optimise, see https://github.com/scikit-optimize/scikit-optimize/issues/978
  - seaborn
  - statsmodels
  - scipy
  - pip
 
  - pip:
    - econml>=0.9
    - xbart
    - tqdm
    - interpret
    - scikit-optimize
    - sklearn-pandas
    - pyreadstat

  