name: reed
channels:
  - defaults
dependencies:
  - python
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - statsmodels
  - scipy
  - pip
 
  - pip:
    - econml>=0.9
    - xbart
    - tqdm
    - interpret
    - scikit-optimize
    - sklearn-pandas
    - pyreadstat
    - jupyter_contrib_nbextensions
variables:
  JUPYTER_CONFIG_PATH: config

  